# Generated by Django 6.0.3 on 2026-04-08 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wife',
            name='husband',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='relations.husband'),
        ),
    ]
