# Generated by Django 6.0.3 on 2026-04-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='file',
            field=models.FileField(upload_to='userdata'),
        ),
    ]
