# Generated by Django 6.0 on 2026-04-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0002_alter_userdata_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='file',
            field=models.ImageField(upload_to='userdata'),
        ),
    ]
